# Generated by Django 5.0 on 2024-06-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(default=0.0, max_length=20)),
                ('user_number', models.CharField(blank=True, max_length=11, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('transaction', models.CharField(default='Current transaction name', max_length=500)),
                ('senders_name', models.CharField(default='Current senders name', max_length=500)),
                ('senders_country', models.CharField(default='Current senders country name', max_length=500)),
                ('recipent_name', models.CharField(default='Current Recipients name', max_length=500)),
                ('recipent_country', models.CharField(default='Current country name', max_length=500)),
                ('recipent_bank', models.CharField(default='Current recipient bank name', max_length=500)),
                ('senders_bank', models.CharField(default='Current senders bank name', max_length=500)),
                ('Total_Transfer_Amount', models.CharField(default='Current Total transfer amount', max_length=500)),
                ('current_date', models.DateField(auto_now=True)),
                ('status_update', models.CharField(default='In progress', max_length=500)),
                ('status_text', models.CharField(default='current overhead or current payments due', max_length=5000)),
                ('estimated_delivery_time', models.CharField(default='time duration of funds unlocking proccess', max_length=500)),
                ('Recipients_IBAN', models.CharField(default='DE31269513110168360295', max_length=500)),
                ('image', models.ImageField(default='image_field', upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
